name: Vercel Production Deployment

env: 
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: 
    push: 
        branch:
        - prod
      
jobs: 
    Deploy-Deployment:
      runs-on: ubunto-latest
      steps: 

          - uses: actions/checkout@v3

          - name: Install Vercel CLI
             run: npm install --global vercel

          - name: Vercel Pull Environment Information
              run: vercel pull --yes --enviornment=deployment --tokent=${{ secrets.VERCEL_TOKEN }}

          - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

          - name: Deploy Project Artifacts
              run: vercel deploy --prebuild --prod --token=${{ secrets.VERCEL_TOKEN }}